//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAgenciaViajes.TipoServicioServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoServicio", Namespace="http://schemas.datacontract.org/2004/07/AgenciaVObjetos")]
    [System.SerializableAttribute()]
    public partial class TipoServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TipoServicioFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoServicioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoServicioNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TipoServicioFecha {
            get {
                return this.TipoServicioFechaField;
            }
            set {
                if ((this.TipoServicioFechaField.Equals(value) != true)) {
                    this.TipoServicioFechaField = value;
                    this.RaisePropertyChanged("TipoServicioFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoServicioID {
            get {
                return this.TipoServicioIDField;
            }
            set {
                if ((this.TipoServicioIDField.Equals(value) != true)) {
                    this.TipoServicioIDField = value;
                    this.RaisePropertyChanged("TipoServicioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoServicioNombre {
            get {
                return this.TipoServicioNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoServicioNombreField, value) != true)) {
                    this.TipoServicioNombreField = value;
                    this.RaisePropertyChanged("TipoServicioNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TipoServicioServiceReference.ISvcTipoServicio")]
    public interface ISvcTipoServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcTipoServicio/Consultar", ReplyAction="http://tempuri.org/ISvcTipoServicio/ConsultarResponse")]
        System.Collections.Generic.List<AppAgenciaViajes.TipoServicioServiceReference.TipoServicio> Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcTipoServicio/Consultar", ReplyAction="http://tempuri.org/ISvcTipoServicio/ConsultarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppAgenciaViajes.TipoServicioServiceReference.TipoServicio>> ConsultarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcTipoServicioChannel : AppAgenciaViajes.TipoServicioServiceReference.ISvcTipoServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcTipoServicioClient : System.ServiceModel.ClientBase<AppAgenciaViajes.TipoServicioServiceReference.ISvcTipoServicio>, AppAgenciaViajes.TipoServicioServiceReference.ISvcTipoServicio {
        
        public SvcTipoServicioClient() {
        }
        
        public SvcTipoServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcTipoServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcTipoServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcTipoServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AppAgenciaViajes.TipoServicioServiceReference.TipoServicio> Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppAgenciaViajes.TipoServicioServiceReference.TipoServicio>> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
    }
}
