//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAgenciaViajes.PasajeroServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pasajero", Namespace="http://schemas.datacontract.org/2004/07/AgenciaVObjetos")]
    [System.SerializableAttribute()]
    public partial class Pasajero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PasajeroFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PasajeroIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDocumentoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDocumento {
            get {
                return this.NumDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocumentoField, value) != true)) {
                    this.NumDocumentoField = value;
                    this.RaisePropertyChanged("NumDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroApellido {
            get {
                return this.PasajeroApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroApellidoField, value) != true)) {
                    this.PasajeroApellidoField = value;
                    this.RaisePropertyChanged("PasajeroApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroCorreo {
            get {
                return this.PasajeroCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroCorreoField, value) != true)) {
                    this.PasajeroCorreoField = value;
                    this.RaisePropertyChanged("PasajeroCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PasajeroFecha {
            get {
                return this.PasajeroFechaField;
            }
            set {
                if ((this.PasajeroFechaField.Equals(value) != true)) {
                    this.PasajeroFechaField = value;
                    this.RaisePropertyChanged("PasajeroFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PasajeroID {
            get {
                return this.PasajeroIDField;
            }
            set {
                if ((this.PasajeroIDField.Equals(value) != true)) {
                    this.PasajeroIDField = value;
                    this.RaisePropertyChanged("PasajeroID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroNombre {
            get {
                return this.PasajeroNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroNombreField, value) != true)) {
                    this.PasajeroNombreField = value;
                    this.RaisePropertyChanged("PasajeroNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroTel {
            get {
                return this.PasajeroTelField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroTelField, value) != true)) {
                    this.PasajeroTelField = value;
                    this.RaisePropertyChanged("PasajeroTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumentoID {
            get {
                return this.TipoDocumentoIDField;
            }
            set {
                if ((this.TipoDocumentoIDField.Equals(value) != true)) {
                    this.TipoDocumentoIDField = value;
                    this.RaisePropertyChanged("TipoDocumentoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PasajeroServiceReference.ISvcPasajero")]
    public interface ISvcPasajero {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPasajero/Consultar", ReplyAction="http://tempuri.org/ISvcPasajero/ConsultarResponse")]
        System.Collections.Generic.List<AppAgenciaViajes.PasajeroServiceReference.Pasajero> Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPasajero/Consultar", ReplyAction="http://tempuri.org/ISvcPasajero/ConsultarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppAgenciaViajes.PasajeroServiceReference.Pasajero>> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPasajero/Insertar", ReplyAction="http://tempuri.org/ISvcPasajero/InsertarResponse")]
        bool Insertar(AppAgenciaViajes.PasajeroServiceReference.Pasajero pasajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPasajero/Insertar", ReplyAction="http://tempuri.org/ISvcPasajero/InsertarResponse")]
        System.Threading.Tasks.Task<bool> InsertarAsync(AppAgenciaViajes.PasajeroServiceReference.Pasajero pasajero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcPasajeroChannel : AppAgenciaViajes.PasajeroServiceReference.ISvcPasajero, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcPasajeroClient : System.ServiceModel.ClientBase<AppAgenciaViajes.PasajeroServiceReference.ISvcPasajero>, AppAgenciaViajes.PasajeroServiceReference.ISvcPasajero {
        
        public SvcPasajeroClient() {
        }
        
        public SvcPasajeroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcPasajeroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcPasajeroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcPasajeroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AppAgenciaViajes.PasajeroServiceReference.Pasajero> Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppAgenciaViajes.PasajeroServiceReference.Pasajero>> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public bool Insertar(AppAgenciaViajes.PasajeroServiceReference.Pasajero pasajero) {
            return base.Channel.Insertar(pasajero);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAsync(AppAgenciaViajes.PasajeroServiceReference.Pasajero pasajero) {
            return base.Channel.InsertarAsync(pasajero);
        }
    }
}
