//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAgenciaViajes.MaletaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Maleta", Namespace="http://schemas.datacontract.org/2004/07/AgenciaVObjetos")]
    [System.SerializableAttribute()]
    public partial class Maleta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaletaAltoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaletaAnchoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaletaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaletaLargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaletaPesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PasajeroIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaletaAlto {
            get {
                return this.MaletaAltoField;
            }
            set {
                if ((this.MaletaAltoField.Equals(value) != true)) {
                    this.MaletaAltoField = value;
                    this.RaisePropertyChanged("MaletaAlto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaletaAncho {
            get {
                return this.MaletaAnchoField;
            }
            set {
                if ((this.MaletaAnchoField.Equals(value) != true)) {
                    this.MaletaAnchoField = value;
                    this.RaisePropertyChanged("MaletaAncho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaletaID {
            get {
                return this.MaletaIDField;
            }
            set {
                if ((this.MaletaIDField.Equals(value) != true)) {
                    this.MaletaIDField = value;
                    this.RaisePropertyChanged("MaletaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaletaLargo {
            get {
                return this.MaletaLargoField;
            }
            set {
                if ((this.MaletaLargoField.Equals(value) != true)) {
                    this.MaletaLargoField = value;
                    this.RaisePropertyChanged("MaletaLargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaletaPeso {
            get {
                return this.MaletaPesoField;
            }
            set {
                if ((this.MaletaPesoField.Equals(value) != true)) {
                    this.MaletaPesoField = value;
                    this.RaisePropertyChanged("MaletaPeso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PasajeroID {
            get {
                return this.PasajeroIDField;
            }
            set {
                if ((this.PasajeroIDField.Equals(value) != true)) {
                    this.PasajeroIDField = value;
                    this.RaisePropertyChanged("PasajeroID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaletaServiceReference.ISvcMaleta")]
    public interface ISvcMaleta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcMaleta/Consultar", ReplyAction="http://tempuri.org/ISvcMaleta/ConsultarResponse")]
        System.Collections.Generic.List<AppAgenciaViajes.MaletaServiceReference.Maleta> Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcMaleta/Consultar", ReplyAction="http://tempuri.org/ISvcMaleta/ConsultarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppAgenciaViajes.MaletaServiceReference.Maleta>> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcMaleta/Insertar", ReplyAction="http://tempuri.org/ISvcMaleta/InsertarResponse")]
        bool Insertar(AppAgenciaViajes.MaletaServiceReference.Maleta Maleta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcMaleta/Insertar", ReplyAction="http://tempuri.org/ISvcMaleta/InsertarResponse")]
        System.Threading.Tasks.Task<bool> InsertarAsync(AppAgenciaViajes.MaletaServiceReference.Maleta Maleta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcMaletaChannel : AppAgenciaViajes.MaletaServiceReference.ISvcMaleta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcMaletaClient : System.ServiceModel.ClientBase<AppAgenciaViajes.MaletaServiceReference.ISvcMaleta>, AppAgenciaViajes.MaletaServiceReference.ISvcMaleta {
        
        public SvcMaletaClient() {
        }
        
        public SvcMaletaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcMaletaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcMaletaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcMaletaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AppAgenciaViajes.MaletaServiceReference.Maleta> Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppAgenciaViajes.MaletaServiceReference.Maleta>> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public bool Insertar(AppAgenciaViajes.MaletaServiceReference.Maleta Maleta) {
            return base.Channel.Insertar(Maleta);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAsync(AppAgenciaViajes.MaletaServiceReference.Maleta Maleta) {
            return base.Channel.InsertarAsync(Maleta);
        }
    }
}
