//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAgenciaViajes.ViajeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Viaje", Namespace="http://schemas.datacontract.org/2004/07/AgenciaVObjetos")]
    [System.SerializableAttribute()]
    public partial class Viaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiudadDestinoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiudadOrigenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NumeroDeMaletasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaisDestinoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaisOrigenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppAgenciaViajes.ViajeServiceReference.Pasajero PasajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PasajeroIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServicioAdicionalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoServicioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ViajeDeFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViajeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadDestinoID {
            get {
                return this.CiudadDestinoIDField;
            }
            set {
                if ((this.CiudadDestinoIDField.Equals(value) != true)) {
                    this.CiudadDestinoIDField = value;
                    this.RaisePropertyChanged("CiudadDestinoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadOrigenID {
            get {
                return this.CiudadOrigenIDField;
            }
            set {
                if ((this.CiudadOrigenIDField.Equals(value) != true)) {
                    this.CiudadOrigenIDField = value;
                    this.RaisePropertyChanged("CiudadOrigenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NumeroDeMaletas {
            get {
                return this.NumeroDeMaletasField;
            }
            set {
                if ((this.NumeroDeMaletasField.Equals(value) != true)) {
                    this.NumeroDeMaletasField = value;
                    this.RaisePropertyChanged("NumeroDeMaletas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaisDestinoID {
            get {
                return this.PaisDestinoIDField;
            }
            set {
                if ((this.PaisDestinoIDField.Equals(value) != true)) {
                    this.PaisDestinoIDField = value;
                    this.RaisePropertyChanged("PaisDestinoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaisOrigenID {
            get {
                return this.PaisOrigenIDField;
            }
            set {
                if ((this.PaisOrigenIDField.Equals(value) != true)) {
                    this.PaisOrigenIDField = value;
                    this.RaisePropertyChanged("PaisOrigenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppAgenciaViajes.ViajeServiceReference.Pasajero Pasajero {
            get {
                return this.PasajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroField, value) != true)) {
                    this.PasajeroField = value;
                    this.RaisePropertyChanged("Pasajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroApellido {
            get {
                return this.PasajeroApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroApellidoField, value) != true)) {
                    this.PasajeroApellidoField = value;
                    this.RaisePropertyChanged("PasajeroApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PasajeroID {
            get {
                return this.PasajeroIDField;
            }
            set {
                if ((this.PasajeroIDField.Equals(value) != true)) {
                    this.PasajeroIDField = value;
                    this.RaisePropertyChanged("PasajeroID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroNombre {
            get {
                return this.PasajeroNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroNombreField, value) != true)) {
                    this.PasajeroNombreField = value;
                    this.RaisePropertyChanged("PasajeroNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServicioAdicionalID {
            get {
                return this.ServicioAdicionalIDField;
            }
            set {
                if ((this.ServicioAdicionalIDField.Equals(value) != true)) {
                    this.ServicioAdicionalIDField = value;
                    this.RaisePropertyChanged("ServicioAdicionalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoServicioID {
            get {
                return this.TipoServicioIDField;
            }
            set {
                if ((this.TipoServicioIDField.Equals(value) != true)) {
                    this.TipoServicioIDField = value;
                    this.RaisePropertyChanged("TipoServicioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ViajeDeFecha {
            get {
                return this.ViajeDeFechaField;
            }
            set {
                if ((this.ViajeDeFechaField.Equals(value) != true)) {
                    this.ViajeDeFechaField = value;
                    this.RaisePropertyChanged("ViajeDeFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViajeID {
            get {
                return this.ViajeIDField;
            }
            set {
                if ((this.ViajeIDField.Equals(value) != true)) {
                    this.ViajeIDField = value;
                    this.RaisePropertyChanged("ViajeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pasajero", Namespace="http://schemas.datacontract.org/2004/07/AgenciaVObjetos")]
    [System.SerializableAttribute()]
    public partial class Pasajero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AppAgenciaViajes.ViajeServiceReference.Maleta> MaletasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PasajeroFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PasajeroIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasajeroTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDocumentoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AppAgenciaViajes.ViajeServiceReference.Maleta> Maletas {
            get {
                return this.MaletasField;
            }
            set {
                if ((object.ReferenceEquals(this.MaletasField, value) != true)) {
                    this.MaletasField = value;
                    this.RaisePropertyChanged("Maletas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDocumento {
            get {
                return this.NumDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocumentoField, value) != true)) {
                    this.NumDocumentoField = value;
                    this.RaisePropertyChanged("NumDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroApellido {
            get {
                return this.PasajeroApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroApellidoField, value) != true)) {
                    this.PasajeroApellidoField = value;
                    this.RaisePropertyChanged("PasajeroApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroCorreo {
            get {
                return this.PasajeroCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroCorreoField, value) != true)) {
                    this.PasajeroCorreoField = value;
                    this.RaisePropertyChanged("PasajeroCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PasajeroFecha {
            get {
                return this.PasajeroFechaField;
            }
            set {
                if ((this.PasajeroFechaField.Equals(value) != true)) {
                    this.PasajeroFechaField = value;
                    this.RaisePropertyChanged("PasajeroFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PasajeroID {
            get {
                return this.PasajeroIDField;
            }
            set {
                if ((this.PasajeroIDField.Equals(value) != true)) {
                    this.PasajeroIDField = value;
                    this.RaisePropertyChanged("PasajeroID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroNombre {
            get {
                return this.PasajeroNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroNombreField, value) != true)) {
                    this.PasajeroNombreField = value;
                    this.RaisePropertyChanged("PasajeroNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasajeroTel {
            get {
                return this.PasajeroTelField;
            }
            set {
                if ((object.ReferenceEquals(this.PasajeroTelField, value) != true)) {
                    this.PasajeroTelField = value;
                    this.RaisePropertyChanged("PasajeroTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumentoID {
            get {
                return this.TipoDocumentoIDField;
            }
            set {
                if ((this.TipoDocumentoIDField.Equals(value) != true)) {
                    this.TipoDocumentoIDField = value;
                    this.RaisePropertyChanged("TipoDocumentoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Maleta", Namespace="http://schemas.datacontract.org/2004/07/AgenciaVObjetos")]
    [System.SerializableAttribute()]
    public partial class Maleta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaletaAltoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaletaAnchoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaletaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaletaLargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaletaPesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PasajeroIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AppAgenciaViajes.ViajeServiceReference.ServicioAdicional> ServiciosAdicionalesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaletaAlto {
            get {
                return this.MaletaAltoField;
            }
            set {
                if ((this.MaletaAltoField.Equals(value) != true)) {
                    this.MaletaAltoField = value;
                    this.RaisePropertyChanged("MaletaAlto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaletaAncho {
            get {
                return this.MaletaAnchoField;
            }
            set {
                if ((this.MaletaAnchoField.Equals(value) != true)) {
                    this.MaletaAnchoField = value;
                    this.RaisePropertyChanged("MaletaAncho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaletaID {
            get {
                return this.MaletaIDField;
            }
            set {
                if ((this.MaletaIDField.Equals(value) != true)) {
                    this.MaletaIDField = value;
                    this.RaisePropertyChanged("MaletaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaletaLargo {
            get {
                return this.MaletaLargoField;
            }
            set {
                if ((this.MaletaLargoField.Equals(value) != true)) {
                    this.MaletaLargoField = value;
                    this.RaisePropertyChanged("MaletaLargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaletaPeso {
            get {
                return this.MaletaPesoField;
            }
            set {
                if ((this.MaletaPesoField.Equals(value) != true)) {
                    this.MaletaPesoField = value;
                    this.RaisePropertyChanged("MaletaPeso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PasajeroID {
            get {
                return this.PasajeroIDField;
            }
            set {
                if ((this.PasajeroIDField.Equals(value) != true)) {
                    this.PasajeroIDField = value;
                    this.RaisePropertyChanged("PasajeroID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AppAgenciaViajes.ViajeServiceReference.ServicioAdicional> ServiciosAdicionales {
            get {
                return this.ServiciosAdicionalesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiciosAdicionalesField, value) != true)) {
                    this.ServiciosAdicionalesField = value;
                    this.RaisePropertyChanged("ServiciosAdicionales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioAdicional", Namespace="http://schemas.datacontract.org/2004/07/AgenciaVObjetos")]
    [System.SerializableAttribute()]
    public partial class ServicioAdicional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServicioAdicionalDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ServicioAdicionalFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServicioAdicionalIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServicioAdicionalDescripcion {
            get {
                return this.ServicioAdicionalDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicioAdicionalDescripcionField, value) != true)) {
                    this.ServicioAdicionalDescripcionField = value;
                    this.RaisePropertyChanged("ServicioAdicionalDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ServicioAdicionalFecha {
            get {
                return this.ServicioAdicionalFechaField;
            }
            set {
                if ((this.ServicioAdicionalFechaField.Equals(value) != true)) {
                    this.ServicioAdicionalFechaField = value;
                    this.RaisePropertyChanged("ServicioAdicionalFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServicioAdicionalID {
            get {
                return this.ServicioAdicionalIDField;
            }
            set {
                if ((this.ServicioAdicionalIDField.Equals(value) != true)) {
                    this.ServicioAdicionalIDField = value;
                    this.RaisePropertyChanged("ServicioAdicionalID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ViajeServiceReference.ISvcViaje")]
    public interface ISvcViaje {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcViaje/Consultar", ReplyAction="http://tempuri.org/ISvcViaje/ConsultarResponse")]
        System.Collections.Generic.List<AppAgenciaViajes.ViajeServiceReference.Viaje> Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcViaje/Consultar", ReplyAction="http://tempuri.org/ISvcViaje/ConsultarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppAgenciaViajes.ViajeServiceReference.Viaje>> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcViaje/Insertar", ReplyAction="http://tempuri.org/ISvcViaje/InsertarResponse")]
        bool Insertar(AppAgenciaViajes.ViajeServiceReference.Viaje Viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcViaje/Insertar", ReplyAction="http://tempuri.org/ISvcViaje/InsertarResponse")]
        System.Threading.Tasks.Task<bool> InsertarAsync(AppAgenciaViajes.ViajeServiceReference.Viaje Viaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcViajeChannel : AppAgenciaViajes.ViajeServiceReference.ISvcViaje, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcViajeClient : System.ServiceModel.ClientBase<AppAgenciaViajes.ViajeServiceReference.ISvcViaje>, AppAgenciaViajes.ViajeServiceReference.ISvcViaje {
        
        public SvcViajeClient() {
        }
        
        public SvcViajeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcViajeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcViajeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcViajeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AppAgenciaViajes.ViajeServiceReference.Viaje> Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppAgenciaViajes.ViajeServiceReference.Viaje>> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public bool Insertar(AppAgenciaViajes.ViajeServiceReference.Viaje Viaje) {
            return base.Channel.Insertar(Viaje);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAsync(AppAgenciaViajes.ViajeServiceReference.Viaje Viaje) {
            return base.Channel.InsertarAsync(Viaje);
        }
    }
}
